"""customer name nullable true

Revision ID: cf48f81d90cf
Revises: 
Create Date: 2024-04-06 23:19:30.436854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf48f81d90cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=20), nullable=True))
        batch_op.drop_column('customername')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customername', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
